\encoding UTF8;

DROP DATABASE IF EXISTS db;
CREATE DATABASE db;

DROP OWNED BY _user_ CASCADE;
DROP USER IF EXISTS _user_;
CREATE USER _user_ WITH PASSWORD 'pass' CREATEDB;

GRANT ALL ON DATABASE db TO _user_;
